  AWSTemplateFormatVersion: '2010-09-09'
  Description: 'CloudFormation for VPC'

  Resources:
    MyVPC:
      Type: 'AWS::EC2::VPC'
      Properties:
        CidrBlock: '172.16.0.0/16'
        EnableDnsSupport: true
        EnableDnsHostnames: true
        Tags:
          - Key: Name
            Value: MyVPC
    PublicSubnet1A:
      Type: 'AWS::EC2::Subnet'
        VpcId: !Ref MyVPC
        CidrBlock: '172.16.1.0/24'
        AvailabilityZone: !Select [0, !GetAZs '']
        MapPublicIpOnLaunch: true
        Tags:
          - Key: Name
            Value: PublicSubnet1A
    AppPrivateSubnet1A:
      Type: 'AWS::EC2::Subnet'
      Properties:
        VpcId: !Ref MyVPC
        CidrBlock: '172.16.2.0/24'
        AvailabilityZone: !Select [0, !GetAZs '']
        Tags:
          - Key: Name
            Value: AppPrivateSubnet1A
    DataPrivateSubnet1A:
      Type: 'AWS::EC2::Subnet'
      Properties:
        VpcId: !Ref MyVPC
        CidrBlock: '172.16.3.0/24'
        AvailabilityZone: !Select [0, !GetAZs '']
        Tags:
          - Key: Name
            Value: DataPrivateSubnet1A
    PublicSubnet2A:
      Type: 'AWS::EC2::Subnet'
      Properties:
        VpcId: !Ref MyVPC
        CidrBlock: '172.16.4.0/24'
        AvailabilityZone: !Select [1, !GetAZs '']
        Tags:
          - Key: Name
            Value: PublicSubnet2A
    AppPrivateSubnet2A:
      Type: 'AWS::EC2::Subnet'
      Properties:
        VpcId: !Ref MyVPC
        CidrBlock: '172.16.5.0/24'
        AvailabilityZone: !Select [1, !GetAZs '']
        Tags:
          - Key: Name
            Value: AppPrivateSubnet2A
    DataPrivateSubnet2A:
      Type: 'AWS::EC2:Subnet'
      Properties:
        VpcId: !Ref MyVPC
        CidrBlock: '172.16.6.0/24'
        AvailabilityZone: !Select [1, !GetAZs '']
        Tags:
          - Key: Name
            Value: DataPrivateSubnet2A
